baseURL: "https://ccanoe.github.io" 
title: Carlos Cano Espinosa, PhD
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        #- name: Books
        #  url: books/
        #  weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        #- name: Courses
        #  url: courses/
        #  weight: 3
        #- name: Data
        #  url: data/
        #  weight: 4 
        - name: Blog
          url: https://www.rovit.ua.es/team/carlos-cano-espinosa/
          weight: 6

params:
    description: "I am an Assistant Professor in the Department of Computer Science and Artificial Intelligence at the University of Alicante (Spain), with research focused on the development of advanced methodologies for medical image analysis."
    author: Carlos Cano Espinosa
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Carlos Cano Espinosa, PhD
          subtitle: "I am an Assistant Professor in the Department of Computer Science and Artificial Intelligence at the University of Alicante (Spain), with research focused on the development of advanced methodologies for medical image analysis."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            #- name: Courses
            #  url: courses/
            #- name: Data
            #  url: data/
            #- name: Books
            #  url: books/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Blog
              url: https://www.rovit.ua.es/team/carlos-cano-espinosa/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:ccanoespinosa@ua.es
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=nPjWT-AAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/ccanoe
        - name: Twitter
          url: https://twitter.com/ccanoespinosa

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Carlos Cano Espinosa"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
